### ISSUE TITLE
TinyDB and JSON AuthProviders

### ISSUE THREAD

**Issue by grimnight** [dgilland/carafe#1]
It would be nice to have alternative AuthProviders, such as [TinyDB](https://github.com/msiemens/tinydb) one.
And possibly a JSON AuthProvider as an example on how to implement new ones.

**Comment by dgilland** [comment]
There's nothing too fancy about the auth provider. I probably could have a base provider class so that it's clearer. There are also several areas of improvement that could be done in the `auth` module as well. But if you treat `carafe.ext.auth.SQLAlchemyAuthProvider` as the base then you could just inherit from that or create your own.

The only required method of a provider is the [identify](https://github.com/dgilland/carafe/blob/master/carafe/ext/auth.py#L37) method  which is called [here](https://github.com/dgilland/carafe/blob/master/carafe/ext/auth.py#L144). The expected return object is a dict containing `id` and `roles` keys (or whatever you set them to via `CARAFE_AUTH_IDENTITY_ID_KEY` and `CARAFE_AUTH_IDENTITY_ROLES_KEY`; the provider class could actually be modified to reference these config values directly when creating the ident dict to prevent key mismatches).

I'm not familiar with TinyDB, but the `SQLAlchemyAuthProvider` uses a database session object to look up the user during the `identify` call. So something like this may work:

``` python
TinyDBAuthProvider(object):
    def __init__(self, db):
        self.db = db

    def identify(self, id):
        ident = {}
        users = self.db.search(where('user_id') == id)

        if users:
            user = users[0]
            ident.update({
                'id': user['user_id'], 
                'roles': user.get('roles', [])
            })

        return ident

db = TinyDB('/path/to/db.json')
auth = Auth()
auth_provider = TinyDBAuthProvider(db)

app = Flask(__name__)
auth.init_app(app, provider=auth_provider)
```

I haven't tested that or anything but does that example address your question about creating an alternative auth provider?

I'm not quite sure what you mean by "JSON AuthProvider". Can you elaborate on that more?

**Comment by grimnight** [comment]
By "JSON AuthProvider" I mean just using pythons own json module, not needing SQLAlchemy.

**Comment by dgilland** [comment]
The AuthProvider is meant to retrieve a user in a datastore. JSON parsing would be handled by some other component.
